export var LOAD_CANDIDATES = "LOAD_CANDIDATES";
export var ADD_ACTIVE_CANDIDATE = "ADD_ACTIVE_CANDIDATE";
export var REMOVE_ACTIVE_CANDIDATE = "REMOVE_ACTIVE_CANDIDATE";
export var UPDATE_DATES = "UPDATE_DATES";
export var LOAD_GRAPHS = "LOAD_GRAPHS";
